/*
ChannelEngine Channel API

ChannelEngine API for channels

API version: 2.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channel

import (
	"encoding/json"
)

// checks if the BulkRefundIdentifierRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkRefundIdentifierRequest{}

// BulkRefundIdentifierRequest struct for BulkRefundIdentifierRequest
type BulkRefundIdentifierRequest struct {
	IdentifierType *RefundByFilterIdentifier `json:"IdentifierType,omitempty"`
	// The value (of the selected type) to filter on
	Models []string `json:"Models,omitempty"`
}

// NewBulkRefundIdentifierRequest instantiates a new BulkRefundIdentifierRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkRefundIdentifierRequest() *BulkRefundIdentifierRequest {
	this := BulkRefundIdentifierRequest{}
	return &this
}

// NewBulkRefundIdentifierRequestWithDefaults instantiates a new BulkRefundIdentifierRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkRefundIdentifierRequestWithDefaults() *BulkRefundIdentifierRequest {
	this := BulkRefundIdentifierRequest{}
	return &this
}

// GetIdentifierType returns the IdentifierType field value if set, zero value otherwise.
func (o *BulkRefundIdentifierRequest) GetIdentifierType() RefundByFilterIdentifier {
	if o == nil || IsNil(o.IdentifierType) {
		var ret RefundByFilterIdentifier
		return ret
	}
	return *o.IdentifierType
}

// GetIdentifierTypeOk returns a tuple with the IdentifierType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkRefundIdentifierRequest) GetIdentifierTypeOk() (*RefundByFilterIdentifier, bool) {
	if o == nil || IsNil(o.IdentifierType) {
		return nil, false
	}
	return o.IdentifierType, true
}

// HasIdentifierType returns a boolean if a field has been set.
func (o *BulkRefundIdentifierRequest) HasIdentifierType() bool {
	if o != nil && !IsNil(o.IdentifierType) {
		return true
	}

	return false
}

// SetIdentifierType gets a reference to the given RefundByFilterIdentifier and assigns it to the IdentifierType field.
func (o *BulkRefundIdentifierRequest) SetIdentifierType(v RefundByFilterIdentifier) {
	o.IdentifierType = &v
}

// GetModels returns the Models field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkRefundIdentifierRequest) GetModels() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Models
}

// GetModelsOk returns a tuple with the Models field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkRefundIdentifierRequest) GetModelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Models) {
		return nil, false
	}
	return o.Models, true
}

// HasModels returns a boolean if a field has been set.
func (o *BulkRefundIdentifierRequest) HasModels() bool {
	if o != nil && !IsNil(o.Models) {
		return true
	}

	return false
}

// SetModels gets a reference to the given []string and assigns it to the Models field.
func (o *BulkRefundIdentifierRequest) SetModels(v []string) {
	o.Models = v
}

func (o BulkRefundIdentifierRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkRefundIdentifierRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdentifierType) {
		toSerialize["IdentifierType"] = o.IdentifierType
	}
	if o.Models != nil {
		toSerialize["Models"] = o.Models
	}
	return toSerialize, nil
}

type NullableBulkRefundIdentifierRequest struct {
	value *BulkRefundIdentifierRequest
	isSet bool
}

func (v NullableBulkRefundIdentifierRequest) Get() *BulkRefundIdentifierRequest {
	return v.value
}

func (v *NullableBulkRefundIdentifierRequest) Set(val *BulkRefundIdentifierRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkRefundIdentifierRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkRefundIdentifierRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkRefundIdentifierRequest(val *BulkRefundIdentifierRequest) *NullableBulkRefundIdentifierRequest {
	return &NullableBulkRefundIdentifierRequest{value: val, isSet: true}
}

func (v NullableBulkRefundIdentifierRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkRefundIdentifierRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


