/*
ChannelEngine Merchant API

ChannelEngine API for merchants

API version: 2.17.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merchant

import (
	"encoding/json"
)

// checks if the ChannelGlobalChannelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelGlobalChannelResponse{}

// ChannelGlobalChannelResponse struct for ChannelGlobalChannelResponse
type ChannelGlobalChannelResponse struct {
	// The country code of the Global Channel.
	CountryCode NullableString `json:"CountryCode,omitempty"`
	// The ID of the Global Channel.
	GlobalChannelId NullableInt32 `json:"GlobalChannelId,omitempty"`
	// The status of the instances.
	Channels []ChannelChannelResponse `json:"Channels,omitempty"`
	// The language code of the Global Channel.
	LanguageCode NullableString `json:"LanguageCode,omitempty"`
	// The name of the Global Channel.
	GlobalChannelName NullableString `json:"GlobalChannelName,omitempty"`
}

// NewChannelGlobalChannelResponse instantiates a new ChannelGlobalChannelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelGlobalChannelResponse() *ChannelGlobalChannelResponse {
	this := ChannelGlobalChannelResponse{}
	return &this
}

// NewChannelGlobalChannelResponseWithDefaults instantiates a new ChannelGlobalChannelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelGlobalChannelResponseWithDefaults() *ChannelGlobalChannelResponse {
	this := ChannelGlobalChannelResponse{}
	return &this
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelGlobalChannelResponse) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode.Get()) {
		var ret string
		return ret
	}
	return *o.CountryCode.Get()
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelGlobalChannelResponse) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CountryCode.Get(), o.CountryCode.IsSet()
}

// HasCountryCode returns a boolean if a field has been set.
func (o *ChannelGlobalChannelResponse) HasCountryCode() bool {
	if o != nil && o.CountryCode.IsSet() {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given NullableString and assigns it to the CountryCode field.
func (o *ChannelGlobalChannelResponse) SetCountryCode(v string) {
	o.CountryCode.Set(&v)
}
// SetCountryCodeNil sets the value for CountryCode to be an explicit nil
func (o *ChannelGlobalChannelResponse) SetCountryCodeNil() {
	o.CountryCode.Set(nil)
}

// UnsetCountryCode ensures that no value is present for CountryCode, not even an explicit nil
func (o *ChannelGlobalChannelResponse) UnsetCountryCode() {
	o.CountryCode.Unset()
}

// GetGlobalChannelId returns the GlobalChannelId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelGlobalChannelResponse) GetGlobalChannelId() int32 {
	if o == nil || IsNil(o.GlobalChannelId.Get()) {
		var ret int32
		return ret
	}
	return *o.GlobalChannelId.Get()
}

// GetGlobalChannelIdOk returns a tuple with the GlobalChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelGlobalChannelResponse) GetGlobalChannelIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalChannelId.Get(), o.GlobalChannelId.IsSet()
}

// HasGlobalChannelId returns a boolean if a field has been set.
func (o *ChannelGlobalChannelResponse) HasGlobalChannelId() bool {
	if o != nil && o.GlobalChannelId.IsSet() {
		return true
	}

	return false
}

// SetGlobalChannelId gets a reference to the given NullableInt32 and assigns it to the GlobalChannelId field.
func (o *ChannelGlobalChannelResponse) SetGlobalChannelId(v int32) {
	o.GlobalChannelId.Set(&v)
}
// SetGlobalChannelIdNil sets the value for GlobalChannelId to be an explicit nil
func (o *ChannelGlobalChannelResponse) SetGlobalChannelIdNil() {
	o.GlobalChannelId.Set(nil)
}

// UnsetGlobalChannelId ensures that no value is present for GlobalChannelId, not even an explicit nil
func (o *ChannelGlobalChannelResponse) UnsetGlobalChannelId() {
	o.GlobalChannelId.Unset()
}

// GetChannels returns the Channels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelGlobalChannelResponse) GetChannels() []ChannelChannelResponse {
	if o == nil {
		var ret []ChannelChannelResponse
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelGlobalChannelResponse) GetChannelsOk() ([]ChannelChannelResponse, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *ChannelGlobalChannelResponse) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []ChannelChannelResponse and assigns it to the Channels field.
func (o *ChannelGlobalChannelResponse) SetChannels(v []ChannelChannelResponse) {
	o.Channels = v
}

// GetLanguageCode returns the LanguageCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelGlobalChannelResponse) GetLanguageCode() string {
	if o == nil || IsNil(o.LanguageCode.Get()) {
		var ret string
		return ret
	}
	return *o.LanguageCode.Get()
}

// GetLanguageCodeOk returns a tuple with the LanguageCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelGlobalChannelResponse) GetLanguageCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LanguageCode.Get(), o.LanguageCode.IsSet()
}

// HasLanguageCode returns a boolean if a field has been set.
func (o *ChannelGlobalChannelResponse) HasLanguageCode() bool {
	if o != nil && o.LanguageCode.IsSet() {
		return true
	}

	return false
}

// SetLanguageCode gets a reference to the given NullableString and assigns it to the LanguageCode field.
func (o *ChannelGlobalChannelResponse) SetLanguageCode(v string) {
	o.LanguageCode.Set(&v)
}
// SetLanguageCodeNil sets the value for LanguageCode to be an explicit nil
func (o *ChannelGlobalChannelResponse) SetLanguageCodeNil() {
	o.LanguageCode.Set(nil)
}

// UnsetLanguageCode ensures that no value is present for LanguageCode, not even an explicit nil
func (o *ChannelGlobalChannelResponse) UnsetLanguageCode() {
	o.LanguageCode.Unset()
}

// GetGlobalChannelName returns the GlobalChannelName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChannelGlobalChannelResponse) GetGlobalChannelName() string {
	if o == nil || IsNil(o.GlobalChannelName.Get()) {
		var ret string
		return ret
	}
	return *o.GlobalChannelName.Get()
}

// GetGlobalChannelNameOk returns a tuple with the GlobalChannelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChannelGlobalChannelResponse) GetGlobalChannelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GlobalChannelName.Get(), o.GlobalChannelName.IsSet()
}

// HasGlobalChannelName returns a boolean if a field has been set.
func (o *ChannelGlobalChannelResponse) HasGlobalChannelName() bool {
	if o != nil && o.GlobalChannelName.IsSet() {
		return true
	}

	return false
}

// SetGlobalChannelName gets a reference to the given NullableString and assigns it to the GlobalChannelName field.
func (o *ChannelGlobalChannelResponse) SetGlobalChannelName(v string) {
	o.GlobalChannelName.Set(&v)
}
// SetGlobalChannelNameNil sets the value for GlobalChannelName to be an explicit nil
func (o *ChannelGlobalChannelResponse) SetGlobalChannelNameNil() {
	o.GlobalChannelName.Set(nil)
}

// UnsetGlobalChannelName ensures that no value is present for GlobalChannelName, not even an explicit nil
func (o *ChannelGlobalChannelResponse) UnsetGlobalChannelName() {
	o.GlobalChannelName.Unset()
}

func (o ChannelGlobalChannelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelGlobalChannelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CountryCode.IsSet() {
		toSerialize["CountryCode"] = o.CountryCode.Get()
	}
	if o.GlobalChannelId.IsSet() {
		toSerialize["GlobalChannelId"] = o.GlobalChannelId.Get()
	}
	if o.Channels != nil {
		toSerialize["Channels"] = o.Channels
	}
	if o.LanguageCode.IsSet() {
		toSerialize["LanguageCode"] = o.LanguageCode.Get()
	}
	if o.GlobalChannelName.IsSet() {
		toSerialize["GlobalChannelName"] = o.GlobalChannelName.Get()
	}
	return toSerialize, nil
}

type NullableChannelGlobalChannelResponse struct {
	value *ChannelGlobalChannelResponse
	isSet bool
}

func (v NullableChannelGlobalChannelResponse) Get() *ChannelGlobalChannelResponse {
	return v.value
}

func (v *NullableChannelGlobalChannelResponse) Set(val *ChannelGlobalChannelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelGlobalChannelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelGlobalChannelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelGlobalChannelResponse(val *ChannelGlobalChannelResponse) *NullableChannelGlobalChannelResponse {
	return &NullableChannelGlobalChannelResponse{value: val, isSet: true}
}

func (v NullableChannelGlobalChannelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelGlobalChannelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


