/*
ChannelEngine Merchant API

ChannelEngine API for merchants

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merchant

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantReturnLineResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantReturnLineResponse{}

// MerchantReturnLineResponse struct for MerchantReturnLineResponse
type MerchantReturnLineResponse struct {
	// The unique product reference used by the Merchant (sku).
	MerchantProductNo NullableString `json:"MerchantProductNo,omitempty"`
	OrderLine *MerchantOrderLineResponse `json:"OrderLine,omitempty"`
	ShipmentStatus *ShipmentLineStatus `json:"ShipmentStatus,omitempty"`
	StockLocation *MerchantStockLocationResponse `json:"StockLocation,omitempty"`
	// Number of items of the product in this return.
	Quantity int32 `json:"Quantity"`
	// Extra data on the returnline. Each item must have an unqiue key
	ExtraData map[string]string `json:"ExtraData,omitempty"`
}

type _MerchantReturnLineResponse MerchantReturnLineResponse

// NewMerchantReturnLineResponse instantiates a new MerchantReturnLineResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantReturnLineResponse(quantity int32) *MerchantReturnLineResponse {
	this := MerchantReturnLineResponse{}
	this.Quantity = quantity
	return &this
}

// NewMerchantReturnLineResponseWithDefaults instantiates a new MerchantReturnLineResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantReturnLineResponseWithDefaults() *MerchantReturnLineResponse {
	this := MerchantReturnLineResponse{}
	return &this
}

// GetMerchantProductNo returns the MerchantProductNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MerchantReturnLineResponse) GetMerchantProductNo() string {
	if o == nil || IsNil(o.MerchantProductNo.Get()) {
		var ret string
		return ret
	}
	return *o.MerchantProductNo.Get()
}

// GetMerchantProductNoOk returns a tuple with the MerchantProductNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantReturnLineResponse) GetMerchantProductNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantProductNo.Get(), o.MerchantProductNo.IsSet()
}

// HasMerchantProductNo returns a boolean if a field has been set.
func (o *MerchantReturnLineResponse) HasMerchantProductNo() bool {
	if o != nil && o.MerchantProductNo.IsSet() {
		return true
	}

	return false
}

// SetMerchantProductNo gets a reference to the given NullableString and assigns it to the MerchantProductNo field.
func (o *MerchantReturnLineResponse) SetMerchantProductNo(v string) {
	o.MerchantProductNo.Set(&v)
}
// SetMerchantProductNoNil sets the value for MerchantProductNo to be an explicit nil
func (o *MerchantReturnLineResponse) SetMerchantProductNoNil() {
	o.MerchantProductNo.Set(nil)
}

// UnsetMerchantProductNo ensures that no value is present for MerchantProductNo, not even an explicit nil
func (o *MerchantReturnLineResponse) UnsetMerchantProductNo() {
	o.MerchantProductNo.Unset()
}

// GetOrderLine returns the OrderLine field value if set, zero value otherwise.
func (o *MerchantReturnLineResponse) GetOrderLine() MerchantOrderLineResponse {
	if o == nil || IsNil(o.OrderLine) {
		var ret MerchantOrderLineResponse
		return ret
	}
	return *o.OrderLine
}

// GetOrderLineOk returns a tuple with the OrderLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantReturnLineResponse) GetOrderLineOk() (*MerchantOrderLineResponse, bool) {
	if o == nil || IsNil(o.OrderLine) {
		return nil, false
	}
	return o.OrderLine, true
}

// HasOrderLine returns a boolean if a field has been set.
func (o *MerchantReturnLineResponse) HasOrderLine() bool {
	if o != nil && !IsNil(o.OrderLine) {
		return true
	}

	return false
}

// SetOrderLine gets a reference to the given MerchantOrderLineResponse and assigns it to the OrderLine field.
func (o *MerchantReturnLineResponse) SetOrderLine(v MerchantOrderLineResponse) {
	o.OrderLine = &v
}

// GetShipmentStatus returns the ShipmentStatus field value if set, zero value otherwise.
func (o *MerchantReturnLineResponse) GetShipmentStatus() ShipmentLineStatus {
	if o == nil || IsNil(o.ShipmentStatus) {
		var ret ShipmentLineStatus
		return ret
	}
	return *o.ShipmentStatus
}

// GetShipmentStatusOk returns a tuple with the ShipmentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantReturnLineResponse) GetShipmentStatusOk() (*ShipmentLineStatus, bool) {
	if o == nil || IsNil(o.ShipmentStatus) {
		return nil, false
	}
	return o.ShipmentStatus, true
}

// HasShipmentStatus returns a boolean if a field has been set.
func (o *MerchantReturnLineResponse) HasShipmentStatus() bool {
	if o != nil && !IsNil(o.ShipmentStatus) {
		return true
	}

	return false
}

// SetShipmentStatus gets a reference to the given ShipmentLineStatus and assigns it to the ShipmentStatus field.
func (o *MerchantReturnLineResponse) SetShipmentStatus(v ShipmentLineStatus) {
	o.ShipmentStatus = &v
}

// GetStockLocation returns the StockLocation field value if set, zero value otherwise.
func (o *MerchantReturnLineResponse) GetStockLocation() MerchantStockLocationResponse {
	if o == nil || IsNil(o.StockLocation) {
		var ret MerchantStockLocationResponse
		return ret
	}
	return *o.StockLocation
}

// GetStockLocationOk returns a tuple with the StockLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantReturnLineResponse) GetStockLocationOk() (*MerchantStockLocationResponse, bool) {
	if o == nil || IsNil(o.StockLocation) {
		return nil, false
	}
	return o.StockLocation, true
}

// HasStockLocation returns a boolean if a field has been set.
func (o *MerchantReturnLineResponse) HasStockLocation() bool {
	if o != nil && !IsNil(o.StockLocation) {
		return true
	}

	return false
}

// SetStockLocation gets a reference to the given MerchantStockLocationResponse and assigns it to the StockLocation field.
func (o *MerchantReturnLineResponse) SetStockLocation(v MerchantStockLocationResponse) {
	o.StockLocation = &v
}

// GetQuantity returns the Quantity field value
func (o *MerchantReturnLineResponse) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *MerchantReturnLineResponse) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *MerchantReturnLineResponse) SetQuantity(v int32) {
	o.Quantity = v
}

// GetExtraData returns the ExtraData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MerchantReturnLineResponse) GetExtraData() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.ExtraData
}

// GetExtraDataOk returns a tuple with the ExtraData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantReturnLineResponse) GetExtraDataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ExtraData) {
		return nil, false
	}
	return &o.ExtraData, true
}

// HasExtraData returns a boolean if a field has been set.
func (o *MerchantReturnLineResponse) HasExtraData() bool {
	if o != nil && !IsNil(o.ExtraData) {
		return true
	}

	return false
}

// SetExtraData gets a reference to the given map[string]string and assigns it to the ExtraData field.
func (o *MerchantReturnLineResponse) SetExtraData(v map[string]string) {
	o.ExtraData = v
}

func (o MerchantReturnLineResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantReturnLineResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MerchantProductNo.IsSet() {
		toSerialize["MerchantProductNo"] = o.MerchantProductNo.Get()
	}
	if !IsNil(o.OrderLine) {
		toSerialize["OrderLine"] = o.OrderLine
	}
	if !IsNil(o.ShipmentStatus) {
		toSerialize["ShipmentStatus"] = o.ShipmentStatus
	}
	if !IsNil(o.StockLocation) {
		toSerialize["StockLocation"] = o.StockLocation
	}
	toSerialize["Quantity"] = o.Quantity
	if o.ExtraData != nil {
		toSerialize["ExtraData"] = o.ExtraData
	}
	return toSerialize, nil
}

func (o *MerchantReturnLineResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantReturnLineResponse := _MerchantReturnLineResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantReturnLineResponse)

	if err != nil {
		return err
	}

	*o = MerchantReturnLineResponse(varMerchantReturnLineResponse)

	return err
}

type NullableMerchantReturnLineResponse struct {
	value *MerchantReturnLineResponse
	isSet bool
}

func (v NullableMerchantReturnLineResponse) Get() *MerchantReturnLineResponse {
	return v.value
}

func (v *NullableMerchantReturnLineResponse) Set(val *MerchantReturnLineResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantReturnLineResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantReturnLineResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantReturnLineResponse(val *MerchantReturnLineResponse) *NullableMerchantReturnLineResponse {
	return &NullableMerchantReturnLineResponse{value: val, isSet: true}
}

func (v NullableMerchantReturnLineResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantReturnLineResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


