/*
ChannelEngine Merchant API

ChannelEngine API for merchants

API version: 2.14.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merchant

import (
	"encoding/json"
)

// checks if the MerchantAcknowledgePurchaseOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantAcknowledgePurchaseOrder{}

// MerchantAcknowledgePurchaseOrder struct for MerchantAcknowledgePurchaseOrder
type MerchantAcknowledgePurchaseOrder struct {
	Identifier NullableString `json:"Identifier,omitempty"`
	MerchantOrderNo NullableString `json:"MerchantOrderNo,omitempty"`
	Lines []MerchantAcknowledgePurchaseOrderLine `json:"Lines,omitempty"`
}

// NewMerchantAcknowledgePurchaseOrder instantiates a new MerchantAcknowledgePurchaseOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantAcknowledgePurchaseOrder() *MerchantAcknowledgePurchaseOrder {
	this := MerchantAcknowledgePurchaseOrder{}
	return &this
}

// NewMerchantAcknowledgePurchaseOrderWithDefaults instantiates a new MerchantAcknowledgePurchaseOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantAcknowledgePurchaseOrderWithDefaults() *MerchantAcknowledgePurchaseOrder {
	this := MerchantAcknowledgePurchaseOrder{}
	return &this
}

// GetIdentifier returns the Identifier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MerchantAcknowledgePurchaseOrder) GetIdentifier() string {
	if o == nil || IsNil(o.Identifier.Get()) {
		var ret string
		return ret
	}
	return *o.Identifier.Get()
}

// GetIdentifierOk returns a tuple with the Identifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantAcknowledgePurchaseOrder) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Identifier.Get(), o.Identifier.IsSet()
}

// HasIdentifier returns a boolean if a field has been set.
func (o *MerchantAcknowledgePurchaseOrder) HasIdentifier() bool {
	if o != nil && o.Identifier.IsSet() {
		return true
	}

	return false
}

// SetIdentifier gets a reference to the given NullableString and assigns it to the Identifier field.
func (o *MerchantAcknowledgePurchaseOrder) SetIdentifier(v string) {
	o.Identifier.Set(&v)
}
// SetIdentifierNil sets the value for Identifier to be an explicit nil
func (o *MerchantAcknowledgePurchaseOrder) SetIdentifierNil() {
	o.Identifier.Set(nil)
}

// UnsetIdentifier ensures that no value is present for Identifier, not even an explicit nil
func (o *MerchantAcknowledgePurchaseOrder) UnsetIdentifier() {
	o.Identifier.Unset()
}

// GetMerchantOrderNo returns the MerchantOrderNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MerchantAcknowledgePurchaseOrder) GetMerchantOrderNo() string {
	if o == nil || IsNil(o.MerchantOrderNo.Get()) {
		var ret string
		return ret
	}
	return *o.MerchantOrderNo.Get()
}

// GetMerchantOrderNoOk returns a tuple with the MerchantOrderNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantAcknowledgePurchaseOrder) GetMerchantOrderNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MerchantOrderNo.Get(), o.MerchantOrderNo.IsSet()
}

// HasMerchantOrderNo returns a boolean if a field has been set.
func (o *MerchantAcknowledgePurchaseOrder) HasMerchantOrderNo() bool {
	if o != nil && o.MerchantOrderNo.IsSet() {
		return true
	}

	return false
}

// SetMerchantOrderNo gets a reference to the given NullableString and assigns it to the MerchantOrderNo field.
func (o *MerchantAcknowledgePurchaseOrder) SetMerchantOrderNo(v string) {
	o.MerchantOrderNo.Set(&v)
}
// SetMerchantOrderNoNil sets the value for MerchantOrderNo to be an explicit nil
func (o *MerchantAcknowledgePurchaseOrder) SetMerchantOrderNoNil() {
	o.MerchantOrderNo.Set(nil)
}

// UnsetMerchantOrderNo ensures that no value is present for MerchantOrderNo, not even an explicit nil
func (o *MerchantAcknowledgePurchaseOrder) UnsetMerchantOrderNo() {
	o.MerchantOrderNo.Unset()
}

// GetLines returns the Lines field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MerchantAcknowledgePurchaseOrder) GetLines() []MerchantAcknowledgePurchaseOrderLine {
	if o == nil {
		var ret []MerchantAcknowledgePurchaseOrderLine
		return ret
	}
	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MerchantAcknowledgePurchaseOrder) GetLinesOk() ([]MerchantAcknowledgePurchaseOrderLine, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *MerchantAcknowledgePurchaseOrder) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given []MerchantAcknowledgePurchaseOrderLine and assigns it to the Lines field.
func (o *MerchantAcknowledgePurchaseOrder) SetLines(v []MerchantAcknowledgePurchaseOrderLine) {
	o.Lines = v
}

func (o MerchantAcknowledgePurchaseOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantAcknowledgePurchaseOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Identifier.IsSet() {
		toSerialize["Identifier"] = o.Identifier.Get()
	}
	if o.MerchantOrderNo.IsSet() {
		toSerialize["MerchantOrderNo"] = o.MerchantOrderNo.Get()
	}
	if o.Lines != nil {
		toSerialize["Lines"] = o.Lines
	}
	return toSerialize, nil
}

type NullableMerchantAcknowledgePurchaseOrder struct {
	value *MerchantAcknowledgePurchaseOrder
	isSet bool
}

func (v NullableMerchantAcknowledgePurchaseOrder) Get() *MerchantAcknowledgePurchaseOrder {
	return v.value
}

func (v *NullableMerchantAcknowledgePurchaseOrder) Set(val *MerchantAcknowledgePurchaseOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantAcknowledgePurchaseOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantAcknowledgePurchaseOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantAcknowledgePurchaseOrder(val *MerchantAcknowledgePurchaseOrder) *NullableMerchantAcknowledgePurchaseOrder {
	return &NullableMerchantAcknowledgePurchaseOrder{value: val, isSet: true}
}

func (v NullableMerchantAcknowledgePurchaseOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantAcknowledgePurchaseOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


